packages: 
  - tightvncserver
  - xfce4-goodies 
  - xfce4
  - netsurf

runcmd:
  # setup VNC
  - export HOME=/root
  - export USER=root
  - mkdir -p /root/.vnc && echo geslo123 | vncpasswd -f > /root/.vnc/passwd
  - chmod 600 /root/.vnc/passwd
  - vncserver && vncserver -kill :1 && echo 'startxfce4 &' >> /root/.vnc/xstartup
  - vncserver -geometry 1920x1080
  # install JDK 8