Vagrant.configure("2") do |config|
    
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "debian"
    config.vm.network "public_network"

    config.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 1024
    end

    
    

    config.vm.provision:shell, inline: "apt-get update"
    
    config.vm.provision:shell, inline: "apt-get install -y tightvncserver xfce4-goodies xfce4 chromium"
    
    # make sure 'root' can launch Chromium
    config.vm.provision:shell, inline: "echo 'CHROMIUM_FLAGS=--no-sandbox' >> /etc/chromium.d/default"

    # set VNC password
    config.vm.provision:shell, inline: "mkdir -p /root/.vnc && echo geslo123 | vncpasswd -f > /root/.vnc/passwd"
    config.vm.provision:shell, inline: "chmod 600 /root/.vnc/passwd" 

    # create and modify 'xstartup' file
    config.vm.provision:shell, inline: "vncserver && vncserver -kill :1 && echo 'startxfce4 &' >> /root/.vnc/xstartup" 

    # start VNC server
    config.vm.provision:shell, inline: "vncserver -geometry 1920x1080"

    # install Java 8    
    config.vm.provision:shell, inline: "cd /home/vagrant && wget https://files-cdn.liferay.com/mirrors/download.oracle.com/otn-pub/java/jdk/8u121-b13/jdk-8u121-linux-x64.tar.gz"
    
    config.vm.provision:shell, inline: "mkdir -p /usr/lib/jvm"
    config.vm.provision:shell, inline: "tar zxvf /home/vagrant/jdk-8u121-linux-x64.tar.gz -C /usr/lib/jvm && rm /home/vagrant/jdk-8u121-linux-x64.tar.gz"
    config.vm.provision:shell, inline: "update-alternatives --install '/usr/bin/java' 'java' '/usr/lib/jvm/jdk1.8.0_121/bin/java' 1"
    config.vm.provision:shell, inline: "update-alternatives --set java /usr/lib/jvm/jdk1.8.0_121/bin/java"
    config.vm.provision:shell, inline: "echo 'PATH=$PATH:/usr/lib/jvm/jdk1.8.0_121/bin' >> /root/.bashrc"

end
